version: '3.8'
services:

  backend:
    container_name: app-backend
    build:
      dockerfile: ./backend/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"

  frontend:
    container_name: app-frontend
    build:
      dockerfile: ./frontend/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"

  database:
    container_name: app-database
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'edbvalencia'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./database/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/data:/data/db
      - ./database/data/log:/var/log/mongodb
    ports:
      - "27017:27017"

  mongo-express:
    container_name: app-client-db
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: 'database'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'edbvalencia'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'sa'
      ME_CONFIG_BASICAUTH_PASSWORD: 'sa'
    depends_on:
      - database
    ports:
      - "8081:8081"
