version: '3.9'
services:

  backend:
    container_name: app-backend
    build:
      dockerfile: backend/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/backend
    links:
      - database
    ports:
      - "8080:8080"

  frontend:
    container_name: app-frontend
    build:
      dockerfile: frontend/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"


  database:
    image: mongo
    restart: unless-stopped
    container_name: app-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'edbvalencia'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./database/init/init-script.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: app-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: 'database'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'edbvalencia'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'root'
      ME_CONFIG_BASICAUTH_PASSWORD: 'root'
    links:
      - database
    ports:
      - "8081:8081"

volumes:
  mongo-data: