FROM openjdk:17

FROM amazoncorretto:17

WORKDIR /app/backend

RUN yum install -y zsh && \
     sh -c "$(curl -fsSL https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t robbyrussell \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/rupa/z/

EXPOSE 8080

CMD ["zsh"]